# BudBot WhatsApp Connector v3.2 - NPM + Chromium Fix
services:
  - type: web
    name: budbot-whatsapp-connector
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BUDBOT_API_URL
        value: https://budbot-ia.onrender.com
      - key: API_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
    healthCheckPath: /health