# Render Stable Config
services:
  - type: web
    name: budbot-whatsapp-connector
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BUDBOT_API_URL
        value: https://budbot-ia.onrender.com
      - key: API_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health