# BudBot WhatsApp Connector v3.0 - Render.com Optimized
services:
  - type: web
    name: budbot-whatsapp-connector
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BUDBOT_API_URL
        value: https://budbot-ia.onrender.com
      - key: API_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
    healthCheckPath: /health